### ISSUE TITLE
How to attach logic simply to pop?

### ISSUE THREAD

**Issue by harkairt** [benPesso/flutter_cupertino_will_pop_scope#10]
Thanks, I really like this package, but I have one issue which I cannot solve

> be sure to update `shouldAddCallbacks` based on the state of your screen, and only set it to `true` when the screen **should not be allowed to pop**

I _would_ like to have some cleanup effect once a screen is swiped/popped, for that purpose I had this tiny widget.

```dart
class OnPop extends StatelessWidget {
  const OnPop({
    required this.child,
    required this.onPop,
    Key? key,
  }) : super(key: key);

  final Widget child;
  final Function() onPop;

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      child: child,
      onWillPop: () {
        onPop.call();
        return true;
      },
    );
  }
}
```

Using this wouldn't work, it always vetos the back gesture, so I have to use a `ConditionalWillPopScope` which always has `shouldAddCallbacks: true` (it must, as I want my callback to be invoked always) then regardless of the return value of `onWillPop` it always "vetos" the pop gesture (even tho `onWillPop` returns `true`)

**Comment by harkairt** [comment]
as per your [comment](https://github.com/benPesso/flutter_cupertino_will_pop_scope/issues/2#issuecomment-775271763) I can solve this issue by doing the cleanup on navigation call site

**Comment by harkairt** [comment]
although, the question still stands, as there could be cases where it is much more convenient to do the cleanup on the corresponding widget

**Comment by benPesso** [comment]
@harkairt First thing that caught my eye is the fact that you're essentially creating a `WillPopScope` widget within another `WillPopScope` widget. I don't see why you would want to set a page's `onPop` logic from another widget, so something like the below makes more sense to me:
```dart
import 'package:cupertino_will_pop_scope/cupertino_will_pop_scope.dart';
import 'package:flutter/material.dart';

class PageWithCleanup extends StatefulWidget {
  const PageWithCleanup({Key? key}) : super(key: key);

  @override
  State<PageWithCleanup> createState() => _PageWithCleanupState();
}

class _PageWithCleanupState extends State<PageWithCleanup> {
  bool _hasChanges = false;
  Future<bool> _alertUnsafePop() async {
    // Do some cleanup, or prompt the user to save.
    // _cleanupAndSave();

    // Return `true` to allow the page to be popped.
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return ConditionalWillPopScope(
      onWillPop: _alertUnsafePop,
      shouldAddCallbacks: _hasChanges,
      child: Container(),
    );
  }
}
```

I guess if you _REALLY_ wanted to have a more "global" pop handler, you could create a static class that would accept the state you wish to clean, and do the cleanup...
```dart
return ConditionalWillPopScope(
  onWillPop: () => GlobalCleaner().cleanup(someStateObject),
  shouldAddCallbacks: _hasChanges,
  child: Container(),
);

```
...but that is the opposite of what a declarative code should do.

**Comment by BugsOverBugs** [comment]
Hey @benPesso @harkairt, I have the same issue.
I want to track when the user leaves the screen and perform some actions, but there is always a veto on swipe back and it does not pop :(

```dart
  Future<bool> _pop() async {
    // _trackPop();
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: _pop,
      child: child,
    );
  }
```
Can you help me with that?

**Comment by benPesso** [comment]
@BugsOverBugs Are you using both the custom transition and the `CupertinoWillPopScope` component?

**Comment by BugsOverBugs** [comment]
> @BugsOverBugs Are you using both the custom transition and the `CupertinoWillPopScope` component?

@benPesso I am using the custom transition like this:
```dart
builders: {
  TargetPlatform.android: useMaterial3
      ? const ZoomPageTransitionsBuilder()
      : androidSdk < 28
          ? const FadeUpwardsPageTransitionsBuilder()
          : const OpenUpwardsPageTransitionsBuilder(),
  TargetPlatform.iOS: const CupertinoWillPopScopePageTransionsBuilder(),
  TargetPlatform.macOS: const CupertinoWillPopScopePageTransionsBuilder(),
  TargetPlatform.windows: const ZoomPageTransitionsBuilder(),
  TargetPlatform.linux: const ZoomPageTransitionsBuilder(),
},
```
And the default `WillPopScope` like above.

Do you mean `ConditionalWillPopScope` with `CupertinoWillPopScope`?
I am not using it, because this `57: assert(_route == ModalRoute.of(context));` triggers too much.

**Comment by BugsOverBugs** [comment]
@benPesso any update on that?
