### ISSUE TITLE
Call onWillPop even if there is no changes

### ISSUE THREAD

**Issue by Bligoubloups** [benPesso/flutter_cupertino_will_pop_scope#2]
Hello @benPesso !
I come from https://github.com/flutter/flutter/issues/14203

So my problem is that the onWillPop callback is not called if there is no changes.

In your example code, if your print something just before the return true it will never be printed.
```
Future<bool> _onWillPop() async {
  if (_hasChanges) {
    print("This is called");
    return false;
  }
  print("This is never called");
  return true;
}
```

If you use the flutter WillPopScope, when you click on the back arrow and there is no changes the `print("This is never called");` will show up.

In my case, I do some state cleanup using bloc because I use a global state that needs to be reset. Something like that:
```
Future<bool> _onWillPop() async {
  _bloc.add(ResetState());
  return true;
}
```

I could just call this `_bloc.add(ResetState());` after the `Navigator.of(context).push()` like that:
```
onPressed: () async {
  await Navigator.of(context)
    .push(MaterialPageRoute(builder: (_) => SecondScreen()));
  _bloc.add(ResetState());
},
```

This works properly but if your ConditionalWillPopScope could call onWillPop even if there is no changes, it would be more like the default WillPopScope.

**Comment by benPesso** [comment]
That can certainly be supported. I'll think of the best way to this, as just "fixing" it to always make the callback might break functionality for people currently using the package.

**Comment by benPesso** [comment]
@Bligoubloups  After further inspection, I believe it would be a better approach for you to implement the cleanup logic elsewhere (on the route's return callback, for example). The route's `scopeWillPopCallback` is not the best place for this. Especially since it is called asynchronously.

As you said, this logic is not specific to the route you're coming from, so it makes more sense to go about it outside of the route, like this:
```dart
Navigator.of(context)
      .push(MaterialPageRoute(builder: (context) => _MySecondScreen()))
      .then(value) => _cleanupAppState();
```

**Comment by Bligoubloups** [comment]
Yes :)

Have a nice day !
