### ISSUE TITLE
Swipe not always detected

### ISSUE THREAD

**Issue by sengerts** [benPesso/flutter_cupertino_will_pop_scope#7]
Hi,

I have an issue with this package. Sometimes, if i do the back swipe gesture in a specific way, the swipe is not detected and the page is just being popped. So, with the same exact implementation, the back swipe is sometimes detected and sometimes not.

EDIT: On one specific IOS device, the back swipe is never detected. On others, it works perfectly

**Comment by benPesso** [comment]
@sengerts The swipe logic is actually the native one from Flutter, and not something I've personally written. Can you confirm whether this issue is present with the default swipe mechanism of Flutter? And can you also please specify the device you're having issues with?

**Comment by sengerts** [comment]
On Android, it happens very often if i disable swiping as my default navigation mode and use a classic navigation bar instead. Then swiping the screen sometimes triggers the action but most of the time it does not. As an example for that in action, I attached a short video of my Oneplus Nord where this behaviour occurs.

https://user-images.githubusercontent.com/5702543/124276437-15818180-db44-11eb-8509-09fb5290ea26.mp4

**Comment by benPesso** [comment]
Can you share your repo, so I can have a look? Doesn't seem like it's relating to my package, but I'll have a look nonetheless.
