### ISSUE TITLE
在iOS上能否监听到右滑的事件？

### ISSUE THREAD

**Issue by Eric-air7** [benPesso/flutter_cupertino_will_pop_scope#8]
在一个页面上，我想监听到右滑的事件，然后手动执行 Navigator.pop(context, data); 去进行数据传递，这个需要怎么使用呢？

**Comment by benPesso** [comment]
@Eric-air7 This is not the proper place to ask questions. This place is for reporting issues with the package itself. You'd have better luck posting in Stackoverflow or Reddit.

That said - if I understood your question correctly (using Google Translate) - I imagine it should be easy enough to wrap your screen with a `GestureDetector` and then do whatever you want when the right gesture is detected.
