### ISSUE TITLE
Not clear how package should be used

### ISSUE THREAD

**Issue by petrnymsa** [benPesso/flutter_cupertino_will_pop_scope#9]
I've expected that this package solves issue where onWillPop is not called upon iOS swipe back gesture. 

In our application we use WillPopScope to determine that current page is popped and return back specific data with Navigator.pop() eg.: 

```dart
onWillPop: () async {
            Navigator.of(context).pop(ReceivedMessageDetailPageResponse.opened(message: state.message));
            return false;
          },
````

With this package, it at leas solved issue that iOS swipe gesture is enabled. However, upon swipe gesture will pop scope is not called. 

Minimal repro sample

```dart
import 'package:cupertino_will_pop_scope/cupertino_will_pop_scope.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class CustomMaterialPageRoute extends MaterialPageRoute {
  @protected
  bool get hasScopedWillPopCallback {
    return false;
  }

  CustomMaterialPageRoute({
    required WidgetBuilder builder,
    RouteSettings? settings,
    bool maintainState = true,
    bool fullscreenDialog = false,
  }) : super(
          builder: builder,
          settings: settings,
          maintainState: maintainState,
          fullscreenDialog: fullscreenDialog,
        );
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            TargetPlatform.android: ZoomPageTransitionsBuilder(),
            TargetPlatform.iOS: CupertinoWillPopScopePageTransionsBuilder(),
          },
        ),
      ),
      home: FirstPage(),
    );
  }
}

class FirstPage extends StatelessWidget {
  const FirstPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text("First page"),
        ),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              final result = await Navigator.of(context)
                  .push(CustomMaterialPageRoute(builder: (_) => SecondPage()));

              print(result);
            },
            child: Text('Second page'),
          ),
        ));
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ConditionalWillPopScope(
      shouldAddCallbacks: true,
      onWillPop: () {
        print('WILL POP');
        return Future.value(true);
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Second'),
        ),
        body: Center(child: Text('Test')),
      ),
    );
  }
}
```

If appBar's back button or HW Android's button is pressed - will pop scope is called (hence print WILL POP). On iOS when screen is popped with swipe gesture, will pop scope is not triggered. 

Thank you for your help

**Comment by benPesso** [comment]
@petrnymsa Sorry for the late response. Got lost in time.

I'm not sure the way you're using the `onWillPop` is correct. That handler is called when a route is already being popped, and you shouldn't be triggering navigation events from it (with your `pop()` call).

My package is really only meant to stop iOS from letting you swipe back when it shouldn't, by letting you hook into a `WillPopScope` and making sure that the swipe gesture listened and upholds the outcome of that logic.

**Comment by petrnymsa** [comment]
> I'm not sure the way you're using the `onWillPop` is correct. That handler is called when a route is already being popped, and you shouldn't be triggering navigation events from it (with your `pop()` call).
> 

Thanks for reply. Is there any other way to return something from current route other than using "pop(result)" ? See https://github.com/flutter/flutter/issues/14203. 

I think this pattern is quite often used -> On popping current screen I want to return some result.

**Comment by benPesso** [comment]
Passing back data from a route is indeed done with `pop()`, which I don't see in your code. The `onWillPop` is used to prevent the route from being popped by returning a futured `false` value. Returning `true` means the route can continue its popping.

As a side note, I highly recommend that you move away from the old imperative way of navigation, and use instead the more modern, declarative way of the Router API (Navigator 2.0). One really nice package for doing that is [GoRouter](https://pub.dev/packages/go_router). As for passing data between routes, it's better to learn how to use Providers and handle state in a declarative manner, which makes the app more resilient and the code more readable.

**Comment by petrnymsa** [comment]
> Passing back data from a route is indeed done with `pop()`, which I don't see in your code. The `onWillPop` is used to prevent the route from being popped by returning a futured `false` value. Returning `true` means the route can continue its popping.
> 
> As a side note, I highly recommend that you move away from the old imperative way of navigation, and use instead the more modern, declarative way of the Router API (Navigator 2.0). One really nice package for doing that is [GoRouter](https://pub.dev/packages/go_router). As for passing data between routes, it's better to learn how to use Providers and handle state in a declarative manner, which makes the app more resilient and the code more readable.

First of all, thank you for your time. 

Not sure if we understand each other. Even if I use Nav 2.0, sometimes it is handy to know if user is trying to pop (with WillpopScope) and do some "business logic". 

For example: user started filling out report form and decided to leave without saving -> on the previous page I would like to know if User filled out form and saved it or not. In this case I could use some provider with model but this is huge overkill for returning single value.... 

I can put together some minimal project If you are interested, but I understand if not as this is something beyond your package.

**Comment by benPesso** [comment]
I think the key concept to understand here becomes clearer if you think of your app as a web app, and not a mobile app. (Which is what the Router API was meant to solve.) Under this light, there's no way for you to pass data back to the previous screen, as the user might choose to just close the app, or load some screen from a bookmark. There's no way to guarantee that the user's next action is the one you want, which forces you to shift your logic to handle everything (safely) on the current screen.

With that in mind, having a "global" state provider that holds the information the user typed on the screen, and being able to check it from any screen (I.e. the "previous" screen) makes a lot more sense.

Regardless of which approach you take, the `onWillPop` is not meant to pass data or manipulate data (run some logic, as you said) in any way. It is only meant to hold logic that helps the app determine whether the user should be allowed to navigate away from the current screen.

The way I would handle your situation is by updating the state on every user input, and triggering a dialog of sorts with `onWillPop` (which will also return `false`). For that, you don't need my package at all. What my package does is simply make it more visible to the user that the navigation was denied. (It also makes using `onWillPop` slightly easier, but that's a secondary feature.)

Does that make sense?
